class Car {
  final int id;
  final String name, description, image, range, price, brand;

  final List<CarDetail> performance;
  final List<CarDetail> batteryAndCharging;
  final List<CarDetail> energyConsumption;
  final List<CarDetail> dimensionAndWeight;
  final List<CarDetail> miscellaneous;
  final List<String> driveTechnology;

  Car(
      {required this.id,
      required this.price,
      required this.brand,
      required this.name,
      required this.description,
      required this.image,
      required this.range,
      required this.performance,
      required this.batteryAndCharging,
      required this.energyConsumption,
      required this.dimensionAndWeight,
      required this.miscellaneous,
      required this.driveTechnology});
}

class CarDetail {
  final String title, body;

  CarDetail(this.title, this.body);
}

var carAudi = [
  Car(
      id: 1,
      price: "£87,675",
      name: "Audi e-tron GT RS",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "280 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "3.3 sec"),
        CarDetail("Top Speed", "250 km/h"),
        CarDetail("Total Power", "475 kW (646 PS)"),
        CarDetail("Total Torque", "830 Nm"),
        CarDetail("Range", "405 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "93.4 kWh"),
        CarDetail("Battery Usable", "85.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "265 kW (DC)"),
        CarDetail("Charge Time ", "9h 15m"),
        CarDetail("FastCharge Time", "17 min"),
        CarDetail("Charge Speed", "45 km/h"),
        CarDetail("FastCharge Speed", "1000 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "405 km (210 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "472 km (180 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "433 km (196 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4990 mm"),
        CarDetail("Width", "1960 mm"),
        CarDetail("Height", "1410 mm"),
        CarDetail("Cargo Volume", "366L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "2 seats"),
        CarDetail("Platform", "VW J1"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£81,915",
      name: "Audi e-tron GT quattro",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "420 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.1 sec"),
        CarDetail("Top Speed", "245 km/h"),
        CarDetail("Total Power", "390 kW (530 PS)"),
        CarDetail("Total Torque", "640 Nm"),
        CarDetail("Range", "420 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "93.4 kWh"),
        CarDetail("Battery Usable", "85.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "265 kW (DC)"),
        CarDetail("Charge Time ", "9h 15m"),
        CarDetail("FastCharge Time", "17 min"),
        CarDetail("Charge Speed", "46 km/h"),
        CarDetail("FastCharge Speed", "1030 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "420 km (202 Wh/km)"),
        CarDetail("WLTP Ratings", "487 km (175 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4990 mm"),
        CarDetail("Width", "1960 mm"),
        CarDetail("Height", "1410 mm"),
        CarDetail("Cargo Volume", "405L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "2 seats"),
        CarDetail("Platform", "VW J1"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£87,675",
      name: "Audi e-tron S",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "280 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.5 sec"),
        CarDetail("Top Speed", "210 km/h"),
        CarDetail("Total Power", "370 kW (503 PS)"),
        CarDetail("Total Torque", "973 Nm"),
        CarDetail("Range", "320 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "95.0 kWh"),
        CarDetail("Battery Usable", "86.5 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "155 kW (DC)"),
        CarDetail("Charge Time ", "9h 15m"),
        CarDetail("FastCharge Time", "26 min"),
        CarDetail("Charge Speed", "35 km/h"),
        CarDetail("FastCharge Speed", "510 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "320 km (270 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "374 km (231 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "343 km (252 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4902 mm"),
        CarDetail("Width", "1976 mm"),
        CarDetail("Height", "1629 mm"),
        CarDetail("Cargo Volume", "660L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MLB"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£42,540",
      name: "Audi Q4 e-tron 35",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "285 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "9.0 sec"),
        CarDetail("Top Speed", "160 km/h"),
        CarDetail("Total Power", "125 kW (170 PS)"),
        CarDetail("Total Torque", "310 Nm"),
        CarDetail("Range", "285 km"),
        CarDetail("Drive Mode", "Rear"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "55.0 kWh"),
        CarDetail("Battery Usable", "52.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "7.2 kW (AC)"),
        CarDetail("FastCharge Power", "118 kW (DC)"),
        CarDetail("Charge Time ", "8h 30m"),
        CarDetail("FastCharge Time", "33 min"),
        CarDetail("Charge Speed", "34 km/h"),
        CarDetail("FastCharge Speed", "360 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "285 km (182 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "341 km (152 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "306 km (170 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4588 mm"),
        CarDetail("Width", "1865 mm"),
        CarDetail("Height", "1632 mm"),
        CarDetail("Cargo Volume", "520L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MEB"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£46,780",
      name: "Audi Q4 e-tron 40",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "405 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "8.5 sec"),
        CarDetail("Top Speed", "160 km/h"),
        CarDetail("Total Power", "150 kW (204 PS)"),
        CarDetail("Total Torque", "310 Nm"),
        CarDetail("Range", "405 km"),
        CarDetail("Drive Mode", "Rear"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "82.0 kWh"),
        CarDetail("Battery Usable", "76.6 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "135 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "33 min"),
        CarDetail("Charge Speed", "49 km/h"),
        CarDetail("FastCharge Speed", "510 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "405 km (189 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "521 km (147 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "447 km (171 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4588 mm"),
        CarDetail("Width", "1865 mm"),
        CarDetail("Height", "1632 mm"),
        CarDetail("Cargo Volume", "520L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MEB"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£53,160",
      name: "Audi Q4 e-tron 50 quattro",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "385 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.2 sec"),
        CarDetail("Top Speed", "180 km/h"),
        CarDetail("Total Power", "220 kW (299 PS)"),
        CarDetail("Total Torque", "460 Nm"),
        CarDetail("Range", "385 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "82.0 kWh"),
        CarDetail("Battery Usable", "76.6 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "135 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "33 min"),
        CarDetail("Charge Speed", "47 km/h"),
        CarDetail("FastCharge Speed", "490 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "385 km (199 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "488 km (157 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "412 km (186 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4588 mm"),
        CarDetail("Width", "1865 mm"),
        CarDetail("Height", "1632 mm"),
        CarDetail("Cargo Volume", "520L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MEB"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£61,275",
      name: "Audi e-tron 50 quattro",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "280 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.8 sec"),
        CarDetail("Top Speed", "190 km/h"),
        CarDetail("Total Power", "230 kW (313 PS)"),
        CarDetail("Total Torque", "540 Nm"),
        CarDetail("Range", "280 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "71.0 kWh"),
        CarDetail("Battery Usable", "64.7 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "120 kW (DC)"),
        CarDetail("Charge Time ", "7 hours"),
        CarDetail("FastCharge Time", "25 min"),
        CarDetail("Charge Speed", "40 km/h"),
        CarDetail("FastCharge Speed", "470 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "280 km (231 Wh/km)"),
        CarDetail("NEDC Ratings", "341 km (190 Wh/km)"),
        CarDetail("WLTP Ratings", "257 km (229 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4901 mm"),
        CarDetail("Width", "1935 mm"),
        CarDetail("Height", "1616 mm"),
        CarDetail("Cargo Volume", "660L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MLB"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£72,175",
      name: "Audi e-tron 55 quattro",
      brand: "Audi",
      description: "",
      image: "assets/images/car_1.png",
      range: "365 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "5.7 sec"),
        CarDetail("Top Speed", "200 km/h"),
        CarDetail("Total Power", "300 kW (408 PS)"),
        CarDetail("Total Torque", "664 Nm"),
        CarDetail("Range", "365 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "n/a")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "95.0 kWh"),
        CarDetail("Battery Usable", "86.5 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "155 kW (DC)"),
        CarDetail("Charge Time ", "11h 15m"),
        CarDetail("FastCharge Time", "26 min"),
        CarDetail("Charge Speed", "39 km/h"),
        CarDetail("FastCharge Speed", "590/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "365 km (237 Wh/km)"),
        CarDetail("NEDC Ratings", "441 km (196 Wh/km)"),
        CarDetail("WLTP Ratings", "369 km (234 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4901 mm"),
        CarDetail("Width", "1935 mm"),
        CarDetail("Height", "1616 mm"),
        CarDetail("Cargo Volume", "660L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "3 seats"),
        CarDetail("Platform", "VW MLB"),
      ],
      driveTechnology: []),
];

var carBmw = [
  Car(
      id: 1,
      price: "£111,905",
      name: "BMW iX M60",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "485 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "3.8 sec"),
        CarDetail("Top Speed", "250 km/h"),
        CarDetail("Total Power", "455 kW (619 PS)"),
        CarDetail("Total Torque", "1100 Nm"),
        CarDetail("Range", "485 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "111.5 kWh"),
        CarDetail("Battery Usable", "105.2 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "200 kW (DC)"),
        CarDetail("Charge Time ", "11h 15m"),
        CarDetail("FastCharge Time", "34 min"),
        CarDetail("Charge Speed", "43 km/h"),
        CarDetail("Fastcharge Speed", "590 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "485 km (217 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "566 km (186 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "499 km (211 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4953 mm"),
        CarDetail("Width", "1967 mm"),
        CarDetail("Height", "1696 mm"),
        CarDetail("Cargo Volume", "500L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£60,970",
      name: "BMW iX3",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "385 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.8 sec"),
        CarDetail("Top Speed", "180 km/h"),
        CarDetail("Total Power", "210 kW (285 PS)"),
        CarDetail("Total Torque", "400 Nm"),
        CarDetail("Range", "385 km"),
        CarDetail("Drive Mode", "Rear"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "80.0 kWh"),
        CarDetail("Battery Usable", "74.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "155 kW (DC)"),
        CarDetail("Charge Time ", "8 hours"),
        CarDetail("FastCharge Time", "31 min"),
        CarDetail("Charge Speed", "49 km/h"),
        CarDetail("FastCharge Speed", "520 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "385 km (192 Wh/km)"),
        CarDetail("NEDC Ratings", "520 km (142 Wh/km)"),
        CarDetail("WLTP Ratings", "460 km (161 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4734 mm"),
        CarDetail("Width", "1891 mm"),
        CarDetail("Height", "1668 mm"),
        CarDetail("Cargo Volume", "510L"),
        CarDetail("Tire Spec", "255/50/R22"),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 seats"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£63,905",
      name: "BMW i4 M50",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "435 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "3.9 sec"),
        CarDetail("Top Speed", "225 km/h"),
        CarDetail("Total Power", "400 kW (544 PS)"),
        CarDetail("Total Torque", "795 Nm"),
        CarDetail("Range", "435 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "83.9 kWh"),
        CarDetail("Battery Usable", "80.7 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "200 kW (DC)"),
        CarDetail("Charge Time ", "8h 45m"),
        CarDetail("FastCharge Time", "30 min"),
        CarDetail("Charge Speed", "50 km/h"),
        CarDetail("FastCharge Speed", "600 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "435 km (186 Wh/km)"),
        CarDetail("WLTP Ratings", "510 km (158 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4783 mm"),
        CarDetail("Width", "1852 mm"),
        CarDetail("Height", "1448 mm"),
        CarDetail("Cargo Volume", "470L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£93,905",
      name: "BMW iX xDrive50",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "505 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.6 sec"),
        CarDetail("Top Speed", "200 km/h"),
        CarDetail("Total Power", "385 kW (523 PS)"),
        CarDetail("Total Torque", "765 Nm"),
        CarDetail("Range", "505 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "111.5 kWh"),
        CarDetail("Battery Usable", "105.2 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "200 kW (DC)"),
        CarDetail("Charge Time ", "11h 15m"),
        CarDetail("FastCharge Time", "34 min"),
        CarDetail("Charge Speed", "45 km/h"),
        CarDetail("FastCharge Speed", "620 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "505 km (208 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "630 km (167 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "549 km (192 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4953 mm"),
        CarDetail("Width", "1967 mm"),
        CarDetail("Height", "1696 mm"),
        CarDetail("Cargo Volume", "500L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£69,905",
      name: "BMW iX xDrive40",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "505 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.1 sec"),
        CarDetail("Top Speed", "200 km/h"),
        CarDetail("Total Power", "240 kW (326 PS)"),
        CarDetail("Total Torque", "630 Nm"),
        CarDetail("Range", "350 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "76.6 kWh"),
        CarDetail("Battery Usable", "71.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "150 kW (DC)"),
        CarDetail("Charge Time ", "7h 45m"),
        CarDetail("FastCharge Time", "31 min"),
        CarDetail("Charge Speed", "46 km/h"),
        CarDetail("FastCharge Speed", "470 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "350 km (203 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "425 km (167 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "372 km (191 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4953 mm"),
        CarDetail("Width", "1967 mm"),
        CarDetail("Height", "1695 mm"),
        CarDetail("Cargo Volume", "500L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£51,905",
      name: "BMW i4 eDrive40",
      brand: "BMW",
      description: "BMW iX3 desc",
      image: "assets/images/car_1.png",
      range: "470 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "5.7 sec"),
        CarDetail("Top Speed", "190 km/h"),
        CarDetail("Total Power", "250 kW (340 PS)"),
        CarDetail("Total Torque", "430 Nm"),
        CarDetail("Range", "470 km"),
        CarDetail("Drive Mode", "Rear"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "83.9 kWh"),
        CarDetail("Battery Usable", "80.7 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "200 kW (DC)"),
        CarDetail("Charge Time ", "8h 45m"),
        CarDetail("FastCharge Time", "30 min"),
        CarDetail("Charge Speed", "54 km/h"),
        CarDetail("FastCharge Speed", "650 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "470 km (172 Wh/km)"),
        CarDetail("WLTP Ratings", "590 km (137 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4783 mm"),
        CarDetail("Width", "1852 mm"),
        CarDetail("Height", "1448 mm"),
        CarDetail("Cargo Volume", "470L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "BMW CLAR"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£33,805",
      name: "BMW i3 120 Ah",
      brand: "BMW",
      description: "",
      image: "assets/images/car_1.png",
      range: "235 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "7.3 sec"),
        CarDetail("Top Speed", "150 km/h"),
        CarDetail("Total Power", "125 kW (170 PS)"),
        CarDetail("Total Torque", "250 Nm"),
        CarDetail("Range", "235 km"),
        CarDetail("Drive Mode", "Rear"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "42.2 kWh"),
        CarDetail("Battery Usable", "37.9 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "49 kW (DC)"),
        CarDetail("Charge Time ", "4h 15m"),
        CarDetail("FastCharge Time", "36 min"),
        CarDetail("Charge Speed", "58 km/h"),
        CarDetail("FastCharge Speed", "270 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "235 km (161 Wh/km)"),
        CarDetail("NEDC Ratings", "359 km (106 Wh/km)"),
        CarDetail("WLTP Ratings", "308 km (123 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4011 mm"),
        CarDetail("Width", "1775 mm"),
        CarDetail("Height", "1598 mm"),
        CarDetail("Cargo Volume", "260L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Hatchback"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];

var carFord = [
  Car(
      id: 1,
      price: "£68,030",
      name: "Ford Mustang Mach-E GT",
      brand: "Ford",
      description: "",
      image: "assets/images/car_1.png",
      range: "425 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.4 sec"),
        CarDetail("Top Speed", "200 km/h"),
        CarDetail("Total Power", "358 kW (487 PS)"),
        CarDetail("Total Torque", "860 Nm"),
        CarDetail("Range", "425 km"),
        CarDetail("Drive Mode", "AWD"),
        CarDetail("MotorsAmount", "1")
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "98.7 kWh"),
        CarDetail("Battery Usable", "91.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "107 kW (DC)"),
        CarDetail("Charge Time ", "9h 45m"),
        CarDetail("FastCharge Time", "47 min"),
        CarDetail("Charge Speed", "44 km/h"),
        CarDetail("FastCharge Speed", "380 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "425 km (214 Wh/km)"),
        CarDetail("WLTP Ratings", "500 km (182 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4743 mm"),
        CarDetail("Width", "1881 mm"),
        CarDetail("Height", "1613 mm"),
        CarDetail("Cargo Volume", "322L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carHonda = [
  Car(
      id: 1,
      price: "£36,865",
      name: "Honda e Advance",
      brand: "Honda",
      description: "",
      image: "assets/images/car_1.png",
      range: "170 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "8.3 sec"),
        CarDetail("Top Speed", "145 km/h"),
        CarDetail("Total Power", "113 kW (154 PS)"),
        CarDetail("Total Torque", "315 Nm"),
        CarDetail("Range", "170 km"),
        CarDetail("Drive Mode", "RWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "35.5 kWh"),
        CarDetail("Battery Usable", "28.5 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Front - Middle"),
        CarDetail("Charge Power", "6.6 kW (AC)"),
        CarDetail("FastCharge Power", "56 kW (DC)"),
        CarDetail("Charge Time ", "5h 15m"),
        CarDetail("FastCharge Time", "36 min"),
        CarDetail("Charge Speed", "33 km/h"),
        CarDetail("FastCharge Speed", "190 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "170 km (168 Wh/km)"),
        CarDetail("WLTP Ratings", "222 km (128 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "3894 mm"),
        CarDetail("Width", "1752 mm"),
        CarDetail("Height", "1512 mm"),
        CarDetail("Cargo Volume", "171L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Hatchback"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carHyundai = [
  Car(
      id: 1,
      price: "€55,500",
      name: "Hyundai IONIQ 5 Long Range AWD",
      brand: "Hyundai",
      description: "",
      image: "assets/images/car_1.png",
      range: "385 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "5.2 sec"),
        CarDetail("Top Speed", "185 km/h"),
        CarDetail("Total Power", "225 kW (306 PS)"),
        CarDetail("Total Torque", "605 Nm"),
        CarDetail("Range", "385 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "77.4 kWh"),
        CarDetail("Battery Usable", "72.5 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "233 kW (DC)"),
        CarDetail("Charge Time ", "7h 45m"),
        CarDetail("FastCharge Time", "16 min"),
        CarDetail("Charge Speed", "50 km/h"),
        CarDetail("FastCharge Speed", "1010 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "385 km (188 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4635 mm"),
        CarDetail("Width", "1890 mm"),
        CarDetail("Height", "1605 mm"),
        CarDetail("Cargo Volume", "No Data"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "HMG E-GMP"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "€45,900",
      name: "Hyundai IONIQ 5 Standard Range AWD",
      brand: "Hyundai",
      description: "",
      image: "assets/images/car_1.png",
      range: "290 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.1 sec"),
        CarDetail("Top Speed", "185 km/h"),
        CarDetail("Total Power", "173 kW (235 PS)"),
        CarDetail("Total Torque", "605 Nm"),
        CarDetail("Range", "290 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "58.0 kWh"),
        CarDetail("Battery Usable", "54.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "175 kW (DC)"),
        CarDetail("Charge Time ", "6 hours"),
        CarDetail("FastCharge Time", "17 min"),
        CarDetail("Charge Speed", "50 km/h"),
        CarDetail("FastCharge Speed", "710 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "290 km (186 Wh/km)"),
        CarDetail("WLTP Ratings", "362 km (149 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4635 mm"),
        CarDetail("Width", "1890 mm"),
        CarDetail("Height", "1605 mm"),
        CarDetail("Cargo Volume", "531L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "HMG E-GMP"),
      ],
      driveTechnology: []),
];
var carLexus = [
  Car(
      id: 1,
      price: "£42,645",
      name: "Lexus UX 300e",
      brand: "Lexus",
      description: "",
      image: "assets/images/car_1.png",
      range: "235 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "7.5 sec"),
        CarDetail("Top Speed", "160 km/h"),
        CarDetail("Total Power", "150 kW (204 PS)"),
        CarDetail("Total Torque", "300 Nm"),
        CarDetail("Range", "235 km"),
        CarDetail("Drive Mode", "FWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "54.3 kWh"),
        CarDetail("Battery Usable", "45.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Rear"),
        CarDetail("Charge Power", "6.6 kW (AC)"),
        CarDetail("FastCharge Power", "35 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "62 min"),
        CarDetail("Charge Speed", "29 km/h"),
        CarDetail("FastCharge Speed", "150 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "235 km (191 Wh/km)"),
        CarDetail("NEDC Ratings", "400 km (113 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "315 km (143 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "305 km (148 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4495 mm"),
        CarDetail("Width", "1840 mm"),
        CarDetail("Height", "1545 mm"),
        CarDetail("Cargo Volume", "367L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "Toyota GA-C"),
      ],
      driveTechnology: []),
];
var carBenz = [
  Car(
      id: 1,
      price: "£102,160",
      name: "Mercedes EQS 450+",
      brand: "Mercedes",
      description: "",
      image: "assets/images/car_1.png",
      range: "640 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.2 sec"),
        CarDetail("Top Speed", "210 km/h"),
        CarDetail("Total Power", "245 kW (333 PS)"),
        CarDetail("Total Torque", "568 Nm"),
        CarDetail("Range", "640 km"),
        CarDetail("Drive Mode", "RWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "120.0 kWh"),
        CarDetail("Battery Usable", "107.8 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "207 kW (DC)"),
        CarDetail("Charge Time ", "11h 45m"),
        CarDetail("FastCharge Time", "32 min"),
        CarDetail("Charge Speed", "56 km/h"),
        CarDetail("FastCharge Speed", "840 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "640 km (168 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "784 km (138 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "631 km (171 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "5216 mm"),
        CarDetail("Width", "1926 mm"),
        CarDetail("Height", "1512 mm"),
        CarDetail("Cargo Volume", "610L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carMG = [
  Car(
      id: 1,
      price: "£29,495",
      name: "MG ZS EV Long Range",
      brand: "MG",
      description: "",
      image: "assets/images/car_1.png",
      range: "365 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "8.4 sec"),
        CarDetail("Top Speed", "175 km/h"),
        CarDetail("Total Power", "115 kW (156 PS)"),
        CarDetail("Total Torque", "280 Nm"),
        CarDetail("Range", "365 km"),
        CarDetail("Drive Mode", "FWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "72.6 kWh"),
        CarDetail("Battery Usable", "68.3 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Front - Middle"),
        CarDetail("Charge Power", "7.4 kW (AC)"),
        CarDetail("FastCharge Power", "94 kW (DC)"),
        CarDetail("Charge Time ", "11 hours"),
        CarDetail("FastCharge Time", "37 min"),
        CarDetail("Charge Speed", "34 km/h"),
        CarDetail("FastCharge Speed", "410 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "365 km (187 Wh/km)"),
        CarDetail("WLTP Ratings", "440 km (155 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4323 mm"),
        CarDetail("Width", "1809 mm"),
        CarDetail("Height", "1649 mm"),
        CarDetail("Cargo Volume", "448L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carMini = [
  Car(
      id: 1,
      price: "£27,000",
      name: "Mini Cooper SE",
      brand: "Mini Cooper",
      description: "",
      image: "assets/images/car_1.png",
      range: "185 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "7.3 sec"),
        CarDetail("Top Speed", "150 km/h"),
        CarDetail("Total Power", "135 kW (184 PS)"),
        CarDetail("Total Torque", "270 Nm"),
        CarDetail("Range", "185 km"),
        CarDetail("Drive Mode", "FWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "32.6 kWh"),
        CarDetail("Battery Usable", "28.9 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "49 kW (DC)"),
        CarDetail("Charge Time ", "3h 15m"),
        CarDetail("FastCharge Time", "29 min"),
        CarDetail("Charge Speed", "60 km/h"),
        CarDetail("FastCharge Speed", "260 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "185 km (156 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "234 km (124 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "203 km (142 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "3850 mm"),
        CarDetail("Width", "1727 mm"),
        CarDetail("Height", "1432 mm"),
        CarDetail("Cargo Volume", "211L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Hatchback"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carNissan = [
  Car(
      id: 1,
      price: "£58,440",
      name: "Nissan Ariya e-4ORCE 87kWh Performance",
      brand: "Nissan",
      description: "",
      image: "assets/images/car_1.png",
      range: "385 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "5.1 sec"),
        CarDetail("Top Speed", "200 km/h"),
        CarDetail("Total Power", "290 kW (394 PS)"),
        CarDetail("Total Torque", "600 Nm"),
        CarDetail("Range", "385 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "91.0 kWh"),
        CarDetail("Battery Usable", "87.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Charge Power", "22 kW (AC)"),
        CarDetail("FastCharge Power", "130 kW (DC)"),
        CarDetail("Charge Time ", "4h 45m"),
        CarDetail("FastCharge Time", "35 min"),
        CarDetail("Charge Speed", "83 km/h"),
        CarDetail("FastCharge Speed", "460 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "385 km (226 Wh/km)"),
        CarDetail("WLTP Ratings", "399 km (218 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4595 mm"),
        CarDetail("Width", "1850 mm"),
        CarDetail("Height", "1660 mm"),
        CarDetail("Cargo Volume", "415L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "No Data"),
        CarDetail("Platform", "RNM CMF-EV"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£33,445",
      name: "Nissan Leaf e+",
      brand: "Nissan",
      description: "",
      image: "assets/images/car_1.png",
      range: "340 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "6.9 sec"),
        CarDetail("Top Speed", "157 km/h"),
        CarDetail("Total Power", "160 kW (218 PS)"),
        CarDetail("Total Torque", "340 Nm"),
        CarDetail("Range", "340 km"),
        CarDetail("Drive Mode", "FWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "62.0 kWh"),
        CarDetail("Battery Usable", "59.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Charge Power", "6.6 kW (AC)"),
        CarDetail("FastCharge Power", "100 kW (DC)"),
        CarDetail("Charge Time ", "10h 45m"),
        CarDetail("FastCharge Time", "37 min"),
        CarDetail("Charge Speed", "32 km/h"),
        CarDetail("FastCharge Speed", "380 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "340 km (174 Wh/km)"),
        CarDetail("WLTP Ratings", "385 km (153 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4490 mm"),
        CarDetail("Width", "1788 mm"),
        CarDetail("Height", "1540 mm"),
        CarDetail("Cargo Volume", "420L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "Hatchback"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "No Data"),
      ],
      driveTechnology: []),
];
var carPorsche = [
  Car(
      id: 1,
      price: "£140,080",
      name: "Porsche Taycan Turbo S Sport Turismo",
      brand: "Porsche",
      description: "",
      image: "assets/images/car_1.png",
      range: "395 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "2.8 sec"),
        CarDetail("Top Speed", "260 km/h"),
        CarDetail("Total Power", "560 kW (761 PS)"),
        CarDetail("Total Torque", "1050 Nm"),
        CarDetail("Range", "395 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "93.4 kWh"),
        CarDetail("Battery Usable", "83.7 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "262 kW (DC)"),
        CarDetail("Charge Time ", "9 hours"),
        CarDetail("FastCharge Time", "19 min"),
        CarDetail("Charge Speed", "44 km/h"),
        CarDetail("FastCharge Speed", "870 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "395 km (212 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "458 km (183 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "430 km (195 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4963 mm"),
        CarDetail("Width", "1966 mm"),
        CarDetail("Height", "1390 mm"),
        CarDetail("Cargo Volume", "405L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Station/Estate"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "VW J1"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£139,280",
      name: "Porsche Taycan Turbo S",
      brand: "Porsche",
      description: "",
      image: "assets/images/car_1.png",
      range: "400 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "2.8 sec"),
        CarDetail("Top Speed", "260 km/h"),
        CarDetail("Total Power", "560 kW (761 PS)"),
        CarDetail("Total Torque", "1050 Nm"),
        CarDetail("Range", "395 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "93.4 kWh"),
        CarDetail("Battery Usable", "83.7 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Right Side - Front"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "262 kW (DC)"),
        CarDetail("Charge Time ", "9 hours"),
        CarDetail("FastCharge Time", "19 min"),
        CarDetail("Charge Speed", "45 km/h"),
        CarDetail("FastCharge Speed", "880 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "400 km (209 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "416 km (201 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "390 km (215 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4963 mm"),
        CarDetail("Width", "1966 mm"),
        CarDetail("Height", "1378 mm"),
        CarDetail("Cargo Volume", "366L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "4 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "VW J1"),
      ],
      driveTechnology: []),
];
var carTesla = [
  Car(
      id: 1,
      price: "£54,990",
      name: "Tesla Model Y Long Range Dual Motor",
      brand: "Tesla",
      description: "",
      image: "assets/images/car_1.png",
      range: "435 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "5.0 sec"),
        CarDetail("Top Speed", "217 km/h"),
        CarDetail("Total Power", "324 kW (441 PS)"),
        CarDetail("Total Torque", "493 Nm"),
        CarDetail("Range", "435 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "82.0 kWh"),
        CarDetail("Battery Usable", "75.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "210 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "30 min"),
        CarDetail("Charge Speed", "54 km/h"),
        CarDetail("FastCharge Speed", "600 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "435 km (172 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "542 km (138 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "533 km (141 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4751 mm"),
        CarDetail("Width", "1921 mm"),
        CarDetail("Height", "1624 mm"),
        CarDetail("Cargo Volume", "854L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "TESLA 3/Y"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£54,990",
      name: "Tesla Model 3 Long Range Dual Motor",
      brand: "Tesla",
      description: "",
      image: "assets/images/car_1.png",
      range: "485 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.4 sec"),
        CarDetail("Top Speed", "233 km/h"),
        CarDetail("Total Power", "324 kW (441 PS)"),
        CarDetail("Total Torque", "493 Nm"),
        CarDetail("Range", "485 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "82.0 kWh"),
        CarDetail("Battery Usable", "75.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "210 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "30 min"),
        CarDetail("Charge Speed", "60 km/h"),
        CarDetail("FastCharge Speed", "670 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "485 km (155 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "614 km (122 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "602 km (125 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4694 mm"),
        CarDetail("Width", "1849 mm"),
        CarDetail("Height", "1443 mm"),
        CarDetail("Cargo Volume", "561L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "Sedan"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "TESLA 3/Y"),
      ],
      driveTechnology: []),
];
var carToyota = [
  Car(
      id: 1,
      price: "£48,350",
      name: "Toyota bZ4X AWD",
      brand: "Toyota",
      description: "",
      image: "assets/images/car_1.png",
      range: "375 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "7.7 sec"),
        CarDetail("Top Speed", "160 km/h"),
        CarDetail("Total Power", "160 kW (218 PS)"),
        CarDetail("Total Torque", "336 Nm"),
        CarDetail("Range", "375 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "71.4 kWh"),
        CarDetail("Battery Usable", "71.4 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Front"),
        CarDetail("Charge Power", "6.6 kW (AC)"),
        CarDetail("FastCharge Power", "150 kW (DC)"),
        CarDetail("Charge Time ", "12h 45m"),
        CarDetail("FastCharge Time", "32 min"),
        CarDetail("Charge Speed", "29 km/h"),
        CarDetail("FastCharge Speed", "490 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "375 km (190 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "461 km (155 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "415 km (172 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4690 mm"),
        CarDetail("Width", "1860 mm"),
        CarDetail("Height", "1600 mm"),
        CarDetail("Cargo Volume", "452L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "TMC E-TNGA"),
      ],
      driveTechnology: []),
];
var carVolvo = [
  Car(
      id: 1,
      price: "£55,550",
      name: "Volvo C40 Recharge Twin Pure Electric",
      brand: "Toyota",
      description: "",
      image: "assets/images/car_1.png",
      range: "350 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.7 sec"),
        CarDetail("Top Speed", "180 km/h"),
        CarDetail("Total Power", "300 kW (408 PS)"),
        CarDetail("Total Torque", "660 Nm"),
        CarDetail("Range", "350 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "78.0 kWh"),
        CarDetail("Battery Usable", "75.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "151 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "32 min"),
        CarDetail("Charge Speed", "44 km/h"),
        CarDetail("FastCharge Speed", "450 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "350 km (214 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "444 km (169 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "415 km (181 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4440 mm"),
        CarDetail("Width", "1873 mm"),
        CarDetail("Height", "1596 mm"),
        CarDetail("Cargo Volume", "419L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "Volvo CMA"),
      ],
      driveTechnology: []),
  Car(
      id: 1,
      price: "£55,550",
      name: "Volvo C40 Recharge Twin Pure Electric",
      brand: "Toyota",
      description: "",
      image: "assets/images/car_1.png",
      range: "350 km",
      performance: [
        CarDetail("Acceleration 0 - 100 km/h", "4.7 sec"),
        CarDetail("Top Speed", "180 km/h"),
        CarDetail("Total Power", "300 kW (408 PS)"),
        CarDetail("Total Torque", "660 Nm"),
        CarDetail("Range", "350 km"),
        CarDetail("Drive Mode", "AWD"),
      ],
      batteryAndCharging: [
        CarDetail("Battery Capacity", "78.0 kWh"),
        CarDetail("Battery Usable", "75.0 kWh"),
        CarDetail("Charge Port", "Type2"),
        CarDetail("FastCharge Port", "CCS"),
        CarDetail("Port Location", "Left Side - Rear"),
        CarDetail("Charge Power", "11 kW (AC)"),
        CarDetail("FastCharge Power", "151 kW (DC)"),
        CarDetail("Charge Time ", "8h 15m"),
        CarDetail("FastCharge Time", "32 min"),
        CarDetail("Charge Speed", "44 km/h"),
        CarDetail("FastCharge Speed", "450 km/h"),
      ],
      energyConsumption: [
        CarDetail("EVDB Real Range", "350 km (214 Wh/km)"),
        CarDetail("WLTP Ratings (TEL)", "444 km (169 Wh/km)"),
        CarDetail("WLTP Ratings (TEH)", "415 km (181 Wh/km)"),
      ],
      dimensionAndWeight: [
        CarDetail("Length", "4440 mm"),
        CarDetail("Width", "1873 mm"),
        CarDetail("Height", "1596 mm"),
        CarDetail("Cargo Volume", "419L"),
        CarDetail("Tire Spec", ""),
      ],
      miscellaneous: [
        CarDetail("Seats", "5 people"),
        CarDetail("Car Body", "SUV"),
        CarDetail("Isofix", "2 Seats"),
        CarDetail("Platform", "Volvo CMA"),
      ],
      driveTechnology: []),
];

List<Car> cars = carAudi +
    carBmw +
    carFord +
    carHonda +
    carHyundai +
    carLexus +
    carBenz +
    carMG +
    carMini +
    carNissan +
    carPorsche +
    carTesla +
    carToyota +
    carVolvo;
